### ISSUE TITLE
Breaks with any reference to 'window'

### ISSUE THREAD

**Issue by benoneal** [mateodelnorte/mockrequire#2]
I have a testing environment set up where window exists. However, when using mockrequire, window appears to no longer exist (even outside the mocked requires), and you can't even console.log(window)... it just throws: ```Error: the error {} was thrown, throw an Error :)```

Adding ``` window: window ``` to the sandbox object fixes this, but I feel this is a bandaid solution.

**Comment by mateodelnorte** [comment]
mockrequire was created for testing node.js modules. Happy to accept a pull
request if you want to update it to work with other module loaders.

**Comment by benoneal** [comment]
Which would you be happier with as a solution? 
a) passing in globals that are required so they can be attached to the sandbox
b) making the sandbox inherit from global
